
keycloak:
  realm: ExampleRealm
  auth-server-url: http://127.0.0.1:8080/auth
  ssl-required: none
  resource: example-app-id
  public-client: true

  security-constraints[0]:
    auth-roles[0]: authenticated-user #user must have `authenticated-user` role to access the resource
    security-collections[0]:
      name: Rest API
      patterns[0]: /stuff/*

  expose-token: true
  enabled: true

server:
  port: 8787

spring:
  application:
    name: Example Service
  datasource:
    password: sa
    username: sa
    url: jdbc:h2:./target/testDb;DB_CLOSE_DELAY=1
    driver-class-name: org.h2.Driver
