
keycloak:
  enabled: true                                 #This enables keyclaok in your application
  realm: example                                #Required name of the Security Realm configured in keycloak
  auth-server-url: http://127.0.0.1:8080/auth   #Required Address for keycloak authentication endpoint
  ssl-required: external                        #SSL Valid [all, external, none] for production use all
  resource: example-app-id
  public-client: false                          #Is the client on a trusted network???
  verify-token-audience: true
  credentials: {                                   #Credentials for the client (The Application)
    secret: 2209b3b5-5e75-42bd-b1e8-c8ad0f25291a
  }
  confidential-port: 0

server:
  port: 8787

spring:
  application:
    name: Example Service
  datasource:
    password: sa
    username: sa
    url: jdbc:h2:./target/testDb;DB_CLOSE_DELAY=1
    driver-class-name: org.h2.Driver
